### ISSUE TITLE
xml.etree.ElementTree.ParseError after upgrade to IOS 16

### ISSUE THREAD

**Issue by dafl-tech-admin** [jameno/Simple-Apple-Health-XML-to-CSV#2]
Getting this error after updating to IOS 16. Change in XML format?

Converting XML File...Traceback (most recent call last):
  File "/Users/XXX/Documents/Data/Health/apple_health_xml_convert.py", line 120, in <module>
    main()
  File "/Users/XXX/Documents/Data/Health/apple_health_xml_convert.py", line 112, in main
    health_df = convert_xml()
                ^^^^^^^^^^^^^
  File "/Users/XXX/Documents/Data/Health/apple_health_xml_convert.py", line 46, in convert_xml
    etree = ET.parse("processed_export.xml")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/xml/etree/ElementTree.py", line 1218, in parse
    tree.parse(source, parser)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/xml/etree/ElementTree.py", line 580, in parse
    self._root = parser._parse_whole(source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
xml.etree.ElementTree.ParseError: syntax error: line 156, column 0

**Comment by jameno** [comment]
Thanks for raising this @github-BR-admin!

You were right, it looks like the iOS 16 Apple Health Export introduced a broken XML DTD for some data types.

I've merged in a fix from #3. Let me know if that solves your issues.
